// OPCUA for Rust
// SPDX-License-Identifier: MPL-2.0
// Copyright (C) 2017-2024 Adam Lock, Einar Omang
//
// This file was autogenerated from tools/schema/schemas/1.0.4/Opc.Ua.Types.bsd by opcua-codegen
//
// DO NOT EDIT THIS FILE
#[derive(Debug, Clone, PartialEq)]
#[derive(Default)]
pub struct AliasNameDataType {
    pub alias_name: crate::qualified_name::QualifiedName,
    pub referenced_nodes: Option<Vec<crate::expanded_node_id::ExpandedNodeId>>,
}
impl crate::MessageInfo for AliasNameDataType {
    fn object_id(&self) -> crate::ObjectId {
        crate::ObjectId::AliasNameDataType_Encoding_DefaultBinary
    }
}
impl crate::BinaryEncoder for AliasNameDataType {
    fn byte_len(&self) -> usize {
        let mut size = 0usize;
        size += self.alias_name.byte_len();
        size += self.referenced_nodes.byte_len();
        size
    }
    #[allow(unused_variables)]
    fn encode<S: std::io::Write>(&self, stream: &mut S) -> crate::EncodingResult<usize> {
        let mut size = 0usize;
        size += self.alias_name.encode(stream)?;
        size += self.referenced_nodes.encode(stream)?;
        Ok(size)
    }
    #[allow(unused_variables)]
    fn decode<S: std::io::Read>(
        stream: &mut S,
        decoding_options: &crate::DecodingOptions,
    ) -> crate::EncodingResult<Self> {
        let alias_name = <crate::qualified_name::QualifiedName as crate::BinaryEncoder>::decode(
            stream,
            decoding_options,
        )?;
        let referenced_nodes = <Option<
            Vec<crate::expanded_node_id::ExpandedNodeId>,
        > as crate::BinaryEncoder>::decode(stream, decoding_options)?;
        Ok(Self {
            alias_name,
            referenced_nodes,
        })
    }
}
