// This file was autogenerated from schemas/1.0.4/Opc.Ua.Types.bsd by opcua-codegen
//
// DO NOT EDIT THIS FILE

// OPCUA for Rust
// SPDX-License-Identifier: MPL-2.0
// Copyright (C) 2017-2024 Adam Lock, Einar Omang
#[allow(unused)]
mod opcua { pub use crate as types; }
#[derive(Debug, Clone, PartialEq)]
#[cfg_attr(
    feature = "json",
    derive(opcua::types::JsonEncodable, opcua::types::JsonDecodable)
)]
#[cfg_attr(feature = "xml", derive(opcua::types::FromXml))]
#[derive(Default)]
pub struct BuildInfo {
    pub product_uri: opcua::types::string::UAString,
    pub manufacturer_name: opcua::types::string::UAString,
    pub product_name: opcua::types::string::UAString,
    pub software_version: opcua::types::string::UAString,
    pub build_number: opcua::types::string::UAString,
    pub build_date: opcua::types::date_time::DateTime,
}
impl opcua::types::MessageInfo for BuildInfo {
    fn type_id(&self) -> opcua::types::ObjectId {
        opcua::types::ObjectId::BuildInfo_Encoding_DefaultBinary
    }
    fn json_type_id(&self) -> opcua::types::ObjectId {
        opcua::types::ObjectId::BuildInfo_Encoding_DefaultJson
    }
    fn xml_type_id(&self) -> opcua::types::ObjectId {
        opcua::types::ObjectId::BuildInfo_Encoding_DefaultXml
    }
}
impl opcua::types::BinaryEncodable for BuildInfo {
    #[allow(unused_variables)]
    fn byte_len(&self, ctx: &opcua::types::Context<'_>) -> usize {
        let mut size = 0usize;
        size += self.product_uri.byte_len(ctx);
        size += self.manufacturer_name.byte_len(ctx);
        size += self.product_name.byte_len(ctx);
        size += self.software_version.byte_len(ctx);
        size += self.build_number.byte_len(ctx);
        size += self.build_date.byte_len(ctx);
        size
    }
    #[allow(unused_variables)]
    fn encode<S: std::io::Write + ?Sized>(
        &self,
        stream: &mut S,
        ctx: &opcua::types::Context<'_>,
    ) -> opcua::types::EncodingResult<usize> {
        let mut size = 0usize;
        size += self.product_uri.encode(stream, ctx)?;
        size += self.manufacturer_name.encode(stream, ctx)?;
        size += self.product_name.encode(stream, ctx)?;
        size += self.software_version.encode(stream, ctx)?;
        size += self.build_number.encode(stream, ctx)?;
        size += self.build_date.encode(stream, ctx)?;
        Ok(size)
    }
}
impl opcua::types::BinaryDecodable for BuildInfo {
    #[allow(unused_variables)]
    fn decode<S: std::io::Read + ?Sized>(
        stream: &mut S,
        ctx: &opcua::types::Context<'_>,
    ) -> opcua::types::EncodingResult<Self> {
        Ok(Self {
            product_uri: opcua::types::BinaryDecodable::decode(stream, ctx)?,
            manufacturer_name: opcua::types::BinaryDecodable::decode(stream, ctx)?,
            product_name: opcua::types::BinaryDecodable::decode(stream, ctx)?,
            software_version: opcua::types::BinaryDecodable::decode(stream, ctx)?,
            build_number: opcua::types::BinaryDecodable::decode(stream, ctx)?,
            build_date: opcua::types::BinaryDecodable::decode(stream, ctx)?,
        })
    }
}
