// This file was autogenerated from schemas/1.0.4/Opc.Ua.Types.bsd by opcua-codegen
//
// DO NOT EDIT THIS FILE

// OPCUA for Rust
// SPDX-License-Identifier: MPL-2.0
// Copyright (C) 2017-2024 Adam Lock, Einar Omang
#[allow(unused)]
mod opcua { pub use crate as types; }
#[derive(Debug, Clone, PartialEq)]
#[cfg_attr(
    feature = "json",
    derive(opcua::types::JsonEncodable, opcua::types::JsonDecodable)
)]
#[cfg_attr(feature = "xml", derive(opcua::types::FromXml))]
#[derive(Default)]
pub struct DatagramWriterGroupTransportDataType {
    pub message_repeat_count: u8,
    pub message_repeat_delay: f64,
}
impl opcua::types::MessageInfo for DatagramWriterGroupTransportDataType {
    fn type_id(&self) -> opcua::types::ObjectId {
        opcua::types::ObjectId::DatagramWriterGroupTransportDataType_Encoding_DefaultBinary
    }
    fn json_type_id(&self) -> opcua::types::ObjectId {
        opcua::types::ObjectId::DatagramWriterGroupTransportDataType_Encoding_DefaultJson
    }
    fn xml_type_id(&self) -> opcua::types::ObjectId {
        opcua::types::ObjectId::DatagramWriterGroupTransportDataType_Encoding_DefaultXml
    }
}
impl opcua::types::BinaryEncodable for DatagramWriterGroupTransportDataType {
    #[allow(unused_variables)]
    fn byte_len(&self, ctx: &opcua::types::Context<'_>) -> usize {
        let mut size = 0usize;
        size += self.message_repeat_count.byte_len(ctx);
        size += self.message_repeat_delay.byte_len(ctx);
        size
    }
    #[allow(unused_variables)]
    fn encode<S: std::io::Write + ?Sized>(
        &self,
        stream: &mut S,
        ctx: &opcua::types::Context<'_>,
    ) -> opcua::types::EncodingResult<usize> {
        let mut size = 0usize;
        size += self.message_repeat_count.encode(stream, ctx)?;
        size += self.message_repeat_delay.encode(stream, ctx)?;
        Ok(size)
    }
}
impl opcua::types::BinaryDecodable for DatagramWriterGroupTransportDataType {
    #[allow(unused_variables)]
    fn decode<S: std::io::Read + ?Sized>(
        stream: &mut S,
        ctx: &opcua::types::Context<'_>,
    ) -> opcua::types::EncodingResult<Self> {
        Ok(Self {
            message_repeat_count: opcua::types::BinaryDecodable::decode(stream, ctx)?,
            message_repeat_delay: opcua::types::BinaryDecodable::decode(stream, ctx)?,
        })
    }
}
