// This file was autogenerated from schemas/1.0.4/Opc.Ua.Types.bsd by opcua-codegen
//
// DO NOT EDIT THIS FILE

// OPCUA for Rust
// SPDX-License-Identifier: MPL-2.0
// Copyright (C) 2017-2024 Adam Lock, Einar Omang
#[allow(unused)]
mod opcua { pub use crate as types; }
#[derive(Debug, Clone, PartialEq)]
#[cfg_attr(feature = "json", serde_with::skip_serializing_none)]
#[cfg_attr(feature = "json", derive(serde::Serialize, serde::Deserialize))]
#[cfg_attr(feature = "json", serde(rename_all = "PascalCase"))]
#[cfg_attr(feature = "xml", derive(opcua::types::FromXml))]
#[derive(Default)]
pub struct DatagramWriterGroupTransportDataType {
    pub message_repeat_count: u8,
    pub message_repeat_delay: f64,
}
impl opcua::types::MessageInfo for DatagramWriterGroupTransportDataType {
    fn type_id(&self) -> opcua::types::ObjectId {
        opcua::types::ObjectId::DatagramWriterGroupTransportDataType_Encoding_DefaultBinary
    }
    fn json_type_id(&self) -> opcua::types::ObjectId {
        opcua::types::ObjectId::DatagramWriterGroupTransportDataType_Encoding_DefaultJson
    }
    fn xml_type_id(&self) -> opcua::types::ObjectId {
        opcua::types::ObjectId::DatagramWriterGroupTransportDataType_Encoding_DefaultXml
    }
}
impl opcua::types::BinaryEncodable for DatagramWriterGroupTransportDataType {
    fn byte_len(&self) -> usize {
        let mut size = 0usize;
        size += self.message_repeat_count.byte_len();
        size += self.message_repeat_delay.byte_len();
        size
    }
    #[allow(unused_variables)]
    fn encode<S: std::io::Write + ?Sized>(
        &self,
        stream: &mut S,
    ) -> opcua::types::EncodingResult<usize> {
        let mut size = 0usize;
        size += self.message_repeat_count.encode(stream)?;
        size += self.message_repeat_delay.encode(stream)?;
        Ok(size)
    }
}
impl opcua::types::BinaryDecodable for DatagramWriterGroupTransportDataType {
    #[allow(unused_variables)]
    fn decode<S: std::io::Read>(
        stream: &mut S,
        decoding_options: &opcua::types::DecodingOptions,
    ) -> opcua::types::EncodingResult<Self> {
        Ok(Self {
            message_repeat_count: opcua::types::BinaryDecodable::decode(
                stream,
                decoding_options,
            )?,
            message_repeat_delay: opcua::types::BinaryDecodable::decode(
                stream,
                decoding_options,
            )?,
        })
    }
}
