// OPCUA for Rust
// SPDX-License-Identifier: MPL-2.0
// Copyright (C) 2017-2024 Adam Lock, Einar Omang
//
// This file was autogenerated from tools/schema/schemas/1.0.4/Opc.Ua.Types.bsd by opcua-codegen
//
// DO NOT EDIT THIS FILE
#[derive(Debug, Clone, PartialEq)]
#[derive(Default)]
pub struct DeleteReferencesItem {
    pub source_node_id: crate::node_id::NodeId,
    pub reference_type_id: crate::node_id::NodeId,
    pub is_forward: bool,
    pub target_node_id: crate::expanded_node_id::ExpandedNodeId,
    pub delete_bidirectional: bool,
}
impl crate::MessageInfo for DeleteReferencesItem {
    fn object_id(&self) -> crate::ObjectId {
        crate::ObjectId::DeleteReferencesItem_Encoding_DefaultBinary
    }
}
impl crate::BinaryEncoder for DeleteReferencesItem {
    fn byte_len(&self) -> usize {
        let mut size = 0usize;
        size += self.source_node_id.byte_len();
        size += self.reference_type_id.byte_len();
        size += self.is_forward.byte_len();
        size += self.target_node_id.byte_len();
        size += self.delete_bidirectional.byte_len();
        size
    }
    #[allow(unused_variables)]
    fn encode<S: std::io::Write>(&self, stream: &mut S) -> crate::EncodingResult<usize> {
        let mut size = 0usize;
        size += self.source_node_id.encode(stream)?;
        size += self.reference_type_id.encode(stream)?;
        size += self.is_forward.encode(stream)?;
        size += self.target_node_id.encode(stream)?;
        size += self.delete_bidirectional.encode(stream)?;
        Ok(size)
    }
    #[allow(unused_variables)]
    fn decode<S: std::io::Read>(
        stream: &mut S,
        decoding_options: &crate::DecodingOptions,
    ) -> crate::EncodingResult<Self> {
        let source_node_id = <crate::node_id::NodeId as crate::BinaryEncoder>::decode(
            stream,
            decoding_options,
        )?;
        let reference_type_id = <crate::node_id::NodeId as crate::BinaryEncoder>::decode(
            stream,
            decoding_options,
        )?;
        let is_forward = <bool as crate::BinaryEncoder>::decode(
            stream,
            decoding_options,
        )?;
        let target_node_id = <crate::expanded_node_id::ExpandedNodeId as crate::BinaryEncoder>::decode(
            stream,
            decoding_options,
        )?;
        let delete_bidirectional = <bool as crate::BinaryEncoder>::decode(
            stream,
            decoding_options,
        )?;
        Ok(Self {
            source_node_id,
            reference_type_id,
            is_forward,
            target_node_id,
            delete_bidirectional,
        })
    }
}
