// OPCUA for Rust
// SPDX-License-Identifier: MPL-2.0
// Copyright (C) 2017-2024 Adam Lock, Einar Omang
//
// This file was autogenerated from tools/schema/schemas/1.0.4/Opc.Ua.Types.bsd by opcua-codegen
//
// DO NOT EDIT THIS FILE
#[derive(Debug, Clone, PartialEq)]
#[derive(Default)]
pub struct HistoryUpdateRequest {
    pub request_header: crate::request_header::RequestHeader,
    pub history_update_details: Option<Vec<crate::extension_object::ExtensionObject>>,
}
impl crate::MessageInfo for HistoryUpdateRequest {
    fn object_id(&self) -> crate::ObjectId {
        crate::ObjectId::HistoryUpdateRequest_Encoding_DefaultBinary
    }
}
impl crate::BinaryEncoder for HistoryUpdateRequest {
    fn byte_len(&self) -> usize {
        let mut size = 0usize;
        size += self.request_header.byte_len();
        size += self.history_update_details.byte_len();
        size
    }
    #[allow(unused_variables)]
    fn encode<S: std::io::Write>(&self, stream: &mut S) -> crate::EncodingResult<usize> {
        let mut size = 0usize;
        size += self.request_header.encode(stream)?;
        size += self.history_update_details.encode(stream)?;
        Ok(size)
    }
    #[allow(unused_variables)]
    fn decode<S: std::io::Read>(
        stream: &mut S,
        decoding_options: &crate::DecodingOptions,
    ) -> crate::EncodingResult<Self> {
        let request_header = <crate::request_header::RequestHeader as crate::BinaryEncoder>::decode(
            stream,
            decoding_options,
        )?;
        let __request_handle = request_header.request_handle;
        let history_update_details = <Option<
            Vec<crate::extension_object::ExtensionObject>,
        > as crate::BinaryEncoder>::decode(stream, decoding_options)
            .map_err(|e| e.with_request_handle(__request_handle))?;
        Ok(Self {
            request_header,
            history_update_details,
        })
    }
}
