// This file was autogenerated from schemas/1.0.4/Opc.Ua.Types.bsd by opcua-codegen
//
// DO NOT EDIT THIS FILE

// OPCUA for Rust
// SPDX-License-Identifier: MPL-2.0
// Copyright (C) 2017-2024 Adam Lock, Einar Omang
#[allow(unused)]
mod opcua { pub use crate as types; }
#[derive(Debug, Clone, PartialEq)]
#[cfg_attr(
    feature = "json",
    derive(opcua::types::JsonEncodable, opcua::types::JsonDecodable)
)]
#[cfg_attr(feature = "xml", derive(opcua::types::FromXml))]
#[derive(Default)]
pub struct PubSubGroupDataType {
    pub name: opcua::types::string::UAString,
    pub enabled: bool,
    pub security_mode: super::enums::MessageSecurityMode,
    pub security_group_id: opcua::types::string::UAString,
    pub security_key_services: Option<
        Vec<super::endpoint_description::EndpointDescription>,
    >,
    pub max_network_message_size: u32,
    pub group_properties: Option<Vec<super::key_value_pair::KeyValuePair>>,
}
impl opcua::types::MessageInfo for PubSubGroupDataType {
    fn type_id(&self) -> opcua::types::ObjectId {
        opcua::types::ObjectId::PubSubGroupDataType_Encoding_DefaultBinary
    }
    fn json_type_id(&self) -> opcua::types::ObjectId {
        opcua::types::ObjectId::PubSubGroupDataType_Encoding_DefaultJson
    }
    fn xml_type_id(&self) -> opcua::types::ObjectId {
        opcua::types::ObjectId::PubSubGroupDataType_Encoding_DefaultXml
    }
}
impl opcua::types::BinaryEncodable for PubSubGroupDataType {
    #[allow(unused_variables)]
    fn byte_len(&self, ctx: &opcua::types::Context<'_>) -> usize {
        let mut size = 0usize;
        size += self.name.byte_len(ctx);
        size += self.enabled.byte_len(ctx);
        size += self.security_mode.byte_len(ctx);
        size += self.security_group_id.byte_len(ctx);
        size += self.security_key_services.byte_len(ctx);
        size += self.max_network_message_size.byte_len(ctx);
        size += self.group_properties.byte_len(ctx);
        size
    }
    #[allow(unused_variables)]
    fn encode<S: std::io::Write + ?Sized>(
        &self,
        stream: &mut S,
        ctx: &opcua::types::Context<'_>,
    ) -> opcua::types::EncodingResult<usize> {
        let mut size = 0usize;
        size += self.name.encode(stream, ctx)?;
        size += self.enabled.encode(stream, ctx)?;
        size += self.security_mode.encode(stream, ctx)?;
        size += self.security_group_id.encode(stream, ctx)?;
        size += self.security_key_services.encode(stream, ctx)?;
        size += self.max_network_message_size.encode(stream, ctx)?;
        size += self.group_properties.encode(stream, ctx)?;
        Ok(size)
    }
}
impl opcua::types::BinaryDecodable for PubSubGroupDataType {
    #[allow(unused_variables)]
    fn decode<S: std::io::Read + ?Sized>(
        stream: &mut S,
        ctx: &opcua::types::Context<'_>,
    ) -> opcua::types::EncodingResult<Self> {
        Ok(Self {
            name: opcua::types::BinaryDecodable::decode(stream, ctx)?,
            enabled: opcua::types::BinaryDecodable::decode(stream, ctx)?,
            security_mode: opcua::types::BinaryDecodable::decode(stream, ctx)?,
            security_group_id: opcua::types::BinaryDecodable::decode(stream, ctx)?,
            security_key_services: opcua::types::BinaryDecodable::decode(stream, ctx)?,
            max_network_message_size: opcua::types::BinaryDecodable::decode(
                stream,
                ctx,
            )?,
            group_properties: opcua::types::BinaryDecodable::decode(stream, ctx)?,
        })
    }
}
