// This file was autogenerated from schemas/1.0.4/Opc.Ua.Types.bsd by opcua-codegen
//
// DO NOT EDIT THIS FILE

// OPCUA for Rust
// SPDX-License-Identifier: MPL-2.0
// Copyright (C) 2017-2024 Adam Lock, Einar Omang
#[allow(unused)]
mod opcua { pub use crate as types; }
#[derive(Debug, Clone, PartialEq)]
#[cfg_attr(
    feature = "json",
    derive(opcua::types::JsonEncodable, opcua::types::JsonDecodable)
)]
#[cfg_attr(feature = "xml", derive(opcua::types::FromXml))]
#[derive(Default)]
pub struct QueryFirstRequest {
    pub request_header: opcua::types::request_header::RequestHeader,
    pub view: super::view_description::ViewDescription,
    pub node_types: Option<Vec<super::node_type_description::NodeTypeDescription>>,
    pub filter: super::content_filter::ContentFilter,
    pub max_data_sets_to_return: u32,
    pub max_references_to_return: u32,
}
impl opcua::types::MessageInfo for QueryFirstRequest {
    fn type_id(&self) -> opcua::types::ObjectId {
        opcua::types::ObjectId::QueryFirstRequest_Encoding_DefaultBinary
    }
    fn json_type_id(&self) -> opcua::types::ObjectId {
        opcua::types::ObjectId::QueryFirstRequest_Encoding_DefaultJson
    }
    fn xml_type_id(&self) -> opcua::types::ObjectId {
        opcua::types::ObjectId::QueryFirstRequest_Encoding_DefaultXml
    }
}
impl opcua::types::BinaryEncodable for QueryFirstRequest {
    #[allow(unused_variables)]
    fn byte_len(&self, ctx: &opcua::types::Context<'_>) -> usize {
        let mut size = 0usize;
        size += self.request_header.byte_len(ctx);
        size += self.view.byte_len(ctx);
        size += self.node_types.byte_len(ctx);
        size += self.filter.byte_len(ctx);
        size += self.max_data_sets_to_return.byte_len(ctx);
        size += self.max_references_to_return.byte_len(ctx);
        size
    }
    #[allow(unused_variables)]
    fn encode<S: std::io::Write + ?Sized>(
        &self,
        stream: &mut S,
        ctx: &opcua::types::Context<'_>,
    ) -> opcua::types::EncodingResult<usize> {
        let mut size = 0usize;
        size += self.request_header.encode(stream, ctx)?;
        size += self.view.encode(stream, ctx)?;
        size += self.node_types.encode(stream, ctx)?;
        size += self.filter.encode(stream, ctx)?;
        size += self.max_data_sets_to_return.encode(stream, ctx)?;
        size += self.max_references_to_return.encode(stream, ctx)?;
        Ok(size)
    }
}
impl opcua::types::BinaryDecodable for QueryFirstRequest {
    #[allow(unused_variables)]
    fn decode<S: std::io::Read + ?Sized>(
        stream: &mut S,
        ctx: &opcua::types::Context<'_>,
    ) -> opcua::types::EncodingResult<Self> {
        let request_header: opcua::types::request_header::RequestHeader = opcua::types::BinaryDecodable::decode(
            stream,
            ctx,
        )?;
        let __request_handle = request_header.request_handle;
        Ok(Self {
            request_header,
            view: opcua::types::BinaryDecodable::decode(stream, ctx)
                .map_err(|e| e.with_request_handle(__request_handle))?,
            node_types: opcua::types::BinaryDecodable::decode(stream, ctx)
                .map_err(|e| e.with_request_handle(__request_handle))?,
            filter: opcua::types::BinaryDecodable::decode(stream, ctx)
                .map_err(|e| e.with_request_handle(__request_handle))?,
            max_data_sets_to_return: opcua::types::BinaryDecodable::decode(stream, ctx)
                .map_err(|e| e.with_request_handle(__request_handle))?,
            max_references_to_return: opcua::types::BinaryDecodable::decode(stream, ctx)
                .map_err(|e| e.with_request_handle(__request_handle))?,
        })
    }
}
