// This file was autogenerated from schemas/1.0.4/Opc.Ua.Types.bsd by opcua-codegen
//
// DO NOT EDIT THIS FILE

// OPCUA for Rust
// SPDX-License-Identifier: MPL-2.0
// Copyright (C) 2017-2024 Adam Lock, Einar Omang
#[allow(unused)]
mod opcua { pub use crate as types; }#[derive(Debug, Clone, PartialEq)]
#[cfg_attr(feature = "json", serde_with::skip_serializing_none)]
#[cfg_attr(feature = "json", derive(serde::Serialize, serde::Deserialize))]
#[cfg_attr(feature = "json", serde(rename_all = "PascalCase"))]
#[cfg_attr(feature = "xml", derive(opcua::types::FromXml))]
#[derive(Default)]
pub struct QueryFirstRequest {
    pub request_header: opcua::types::request_header::RequestHeader,
    pub view: super::view_description::ViewDescription,
    pub node_types: Option<Vec<super::node_type_description::NodeTypeDescription>>,
    pub filter: super::content_filter::ContentFilter,
    pub max_data_sets_to_return: u32,
    pub max_references_to_return: u32,
}
impl opcua::types::MessageInfo for QueryFirstRequest {
    fn type_id(&self) -> opcua::types::ObjectId {
        opcua::types::ObjectId::QueryFirstRequest_Encoding_DefaultBinary
    }
    fn json_type_id(&self) -> opcua::types::ObjectId {
        opcua::types::ObjectId::QueryFirstRequest_Encoding_DefaultJson
    }
    fn xml_type_id(&self) -> opcua::types::ObjectId {
        opcua::types::ObjectId::QueryFirstRequest_Encoding_DefaultXml
    }
}
impl opcua::types::BinaryEncodable for QueryFirstRequest {
    fn byte_len(&self) -> usize {
        let mut size = 0usize;
        size += self.request_header.byte_len();
        size += self.view.byte_len();
        size += self.node_types.byte_len();
        size += self.filter.byte_len();
        size += self.max_data_sets_to_return.byte_len();
        size += self.max_references_to_return.byte_len();
        size
    }
    #[allow(unused_variables)]
    fn encode<S: std::io::Write>(
        &self,
        stream: &mut S,
    ) -> opcua::types::EncodingResult<usize> {
        let mut size = 0usize;
        size += self.request_header.encode(stream)?;
        size += self.view.encode(stream)?;
        size += self.node_types.encode(stream)?;
        size += self.filter.encode(stream)?;
        size += self.max_data_sets_to_return.encode(stream)?;
        size += self.max_references_to_return.encode(stream)?;
        Ok(size)
    }
    #[allow(unused_variables)]
    fn decode<S: std::io::Read>(
        stream: &mut S,
        decoding_options: &opcua::types::DecodingOptions,
    ) -> opcua::types::EncodingResult<Self> {
        let request_header = <opcua::types::request_header::RequestHeader as opcua::types::BinaryEncodable>::decode(
            stream,
            decoding_options,
        )?;
        let __request_handle = request_header.request_handle;
        let view = <super::view_description::ViewDescription as opcua::types::BinaryEncodable>::decode(
                stream,
                decoding_options,
            )
            .map_err(|e| e.with_request_handle(__request_handle))?;
        let node_types = <Option<
            Vec<super::node_type_description::NodeTypeDescription>,
        > as opcua::types::BinaryEncodable>::decode(stream, decoding_options)
            .map_err(|e| e.with_request_handle(__request_handle))?;
        let filter = <super::content_filter::ContentFilter as opcua::types::BinaryEncodable>::decode(
                stream,
                decoding_options,
            )
            .map_err(|e| e.with_request_handle(__request_handle))?;
        let max_data_sets_to_return = <u32 as opcua::types::BinaryEncodable>::decode(
                stream,
                decoding_options,
            )
            .map_err(|e| e.with_request_handle(__request_handle))?;
        let max_references_to_return = <u32 as opcua::types::BinaryEncodable>::decode(
                stream,
                decoding_options,
            )
            .map_err(|e| e.with_request_handle(__request_handle))?;
        Ok(Self {
            request_header,
            view,
            node_types,
            filter,
            max_data_sets_to_return,
            max_references_to_return,
        })
    }
}
