// OPCUA for Rust
// SPDX-License-Identifier: MPL-2.0
// Copyright (C) 2017-2024 Adam Lock, Einar Omang
//
// This file was autogenerated from tools/schema/schemas/1.0.4/Opc.Ua.Types.bsd by opcua-codegen
//
// DO NOT EDIT THIS FILE
#[derive(Debug, Clone, PartialEq)]
#[derive(Default)]
pub struct Range {
    pub low: f64,
    pub high: f64,
}
impl crate::MessageInfo for Range {
    fn object_id(&self) -> crate::ObjectId {
        crate::ObjectId::Range_Encoding_DefaultBinary
    }
}
impl crate::BinaryEncoder for Range {
    fn byte_len(&self) -> usize {
        let mut size = 0usize;
        size += self.low.byte_len();
        size += self.high.byte_len();
        size
    }
    #[allow(unused_variables)]
    fn encode<S: std::io::Write>(&self, stream: &mut S) -> crate::EncodingResult<usize> {
        let mut size = 0usize;
        size += self.low.encode(stream)?;
        size += self.high.encode(stream)?;
        Ok(size)
    }
    #[allow(unused_variables)]
    fn decode<S: std::io::Read>(
        stream: &mut S,
        decoding_options: &crate::DecodingOptions,
    ) -> crate::EncodingResult<Self> {
        let low = <f64 as crate::BinaryEncoder>::decode(stream, decoding_options)?;
        let high = <f64 as crate::BinaryEncoder>::decode(stream, decoding_options)?;
        Ok(Self { low, high })
    }
}
