// OPCUA for Rust
// SPDX-License-Identifier: MPL-2.0
// Copyright (C) 2017-2024 Adam Lock, Einar Omang
//
// This file was autogenerated from tools/schema/schemas/1.0.4/Opc.Ua.Types.bsd by opcua-codegen
//
// DO NOT EDIT THIS FILE
#[derive(Debug, Clone, PartialEq)]
#[derive(Default)]
pub struct ServerOnNetwork {
    pub record_id: u32,
    pub server_name: crate::string::UAString,
    pub discovery_url: crate::string::UAString,
    pub server_capabilities: Option<Vec<crate::string::UAString>>,
}
impl crate::MessageInfo for ServerOnNetwork {
    fn object_id(&self) -> crate::ObjectId {
        crate::ObjectId::ServerOnNetwork_Encoding_DefaultBinary
    }
}
impl crate::BinaryEncoder for ServerOnNetwork {
    fn byte_len(&self) -> usize {
        let mut size = 0usize;
        size += self.record_id.byte_len();
        size += self.server_name.byte_len();
        size += self.discovery_url.byte_len();
        size += self.server_capabilities.byte_len();
        size
    }
    #[allow(unused_variables)]
    fn encode<S: std::io::Write>(&self, stream: &mut S) -> crate::EncodingResult<usize> {
        let mut size = 0usize;
        size += self.record_id.encode(stream)?;
        size += self.server_name.encode(stream)?;
        size += self.discovery_url.encode(stream)?;
        size += self.server_capabilities.encode(stream)?;
        Ok(size)
    }
    #[allow(unused_variables)]
    fn decode<S: std::io::Read>(
        stream: &mut S,
        decoding_options: &crate::DecodingOptions,
    ) -> crate::EncodingResult<Self> {
        let record_id = <u32 as crate::BinaryEncoder>::decode(stream, decoding_options)?;
        let server_name = <crate::string::UAString as crate::BinaryEncoder>::decode(
            stream,
            decoding_options,
        )?;
        let discovery_url = <crate::string::UAString as crate::BinaryEncoder>::decode(
            stream,
            decoding_options,
        )?;
        let server_capabilities = <Option<
            Vec<crate::string::UAString>,
        > as crate::BinaryEncoder>::decode(stream, decoding_options)?;
        Ok(Self {
            record_id,
            server_name,
            discovery_url,
            server_capabilities,
        })
    }
}
