// This file was autogenerated from tools/schema/schemas/1.0.4/Opc.Ua.Types.bsd by opcua-codegen
//
// DO NOT EDIT THIS FILE

// OPCUA for Rust
// SPDX-License-Identifier: MPL-2.0
// Copyright (C) 2017-2024 Adam Lock, Einar Omang
#[allow(unused)]
mod opcua { pub use crate as types; }#[derive(Debug, Clone, PartialEq)]
pub struct ServerStatusDataType {
    pub start_time: opcua::types::date_time::DateTime,
    pub current_time: opcua::types::date_time::DateTime,
    pub state: super::enums::ServerState,
    pub build_info: super::build_info::BuildInfo,
    pub seconds_till_shutdown: u32,
    pub shutdown_reason: opcua::types::localized_text::LocalizedText,
}
impl opcua::types::MessageInfo for ServerStatusDataType {
    fn object_id(&self) -> opcua::types::ObjectId {
        opcua::types::ObjectId::ServerStatusDataType_Encoding_DefaultBinary
    }
}
impl opcua::types::BinaryEncoder for ServerStatusDataType {
    fn byte_len(&self) -> usize {
        let mut size = 0usize;
        size += self.start_time.byte_len();
        size += self.current_time.byte_len();
        size += self.state.byte_len();
        size += self.build_info.byte_len();
        size += self.seconds_till_shutdown.byte_len();
        size += self.shutdown_reason.byte_len();
        size
    }
    #[allow(unused_variables)]
    fn encode<S: std::io::Write>(
        &self,
        stream: &mut S,
    ) -> opcua::types::EncodingResult<usize> {
        let mut size = 0usize;
        size += self.start_time.encode(stream)?;
        size += self.current_time.encode(stream)?;
        size += self.state.encode(stream)?;
        size += self.build_info.encode(stream)?;
        size += self.seconds_till_shutdown.encode(stream)?;
        size += self.shutdown_reason.encode(stream)?;
        Ok(size)
    }
    #[allow(unused_variables)]
    fn decode<S: std::io::Read>(
        stream: &mut S,
        decoding_options: &opcua::types::DecodingOptions,
    ) -> opcua::types::EncodingResult<Self> {
        let start_time = <opcua::types::date_time::DateTime as opcua::types::BinaryEncoder>::decode(
            stream,
            decoding_options,
        )?;
        let current_time = <opcua::types::date_time::DateTime as opcua::types::BinaryEncoder>::decode(
            stream,
            decoding_options,
        )?;
        let state = <super::enums::ServerState as opcua::types::BinaryEncoder>::decode(
            stream,
            decoding_options,
        )?;
        let build_info = <super::build_info::BuildInfo as opcua::types::BinaryEncoder>::decode(
            stream,
            decoding_options,
        )?;
        let seconds_till_shutdown = <u32 as opcua::types::BinaryEncoder>::decode(
            stream,
            decoding_options,
        )?;
        let shutdown_reason = <opcua::types::localized_text::LocalizedText as opcua::types::BinaryEncoder>::decode(
            stream,
            decoding_options,
        )?;
        Ok(Self {
            start_time,
            current_time,
            state,
            build_info,
            seconds_till_shutdown,
            shutdown_reason,
        })
    }
}
