// This file was autogenerated from schemas/1.0.4/Opc.Ua.Types.bsd by opcua-codegen
//
// DO NOT EDIT THIS FILE

// OPCUA for Rust
// SPDX-License-Identifier: MPL-2.0
// Copyright (C) 2017-2024 Adam Lock, Einar Omang
#[allow(unused)]
mod opcua { pub use crate as types; }#[derive(Debug, Clone, PartialEq)]
#[cfg_attr(feature = "json", serde_with::skip_serializing_none)]
#[cfg_attr(feature = "json", derive(serde::Serialize, serde::Deserialize))]
#[cfg_attr(feature = "json", serde(rename_all = "PascalCase"))]
#[cfg_attr(feature = "xml", derive(opcua::types::FromXml))]
#[derive(Default)]
pub struct SessionlessInvokeRequestType {
    pub uris_version: u32,
    pub namespace_uris: Option<Vec<opcua::types::string::UAString>>,
    pub server_uris: Option<Vec<opcua::types::string::UAString>>,
    pub locale_ids: Option<Vec<opcua::types::string::UAString>>,
    pub service_id: u32,
}
impl opcua::types::MessageInfo for SessionlessInvokeRequestType {
    fn type_id(&self) -> opcua::types::ObjectId {
        opcua::types::ObjectId::SessionlessInvokeRequestType_Encoding_DefaultBinary
    }
    fn json_type_id(&self) -> opcua::types::ObjectId {
        opcua::types::ObjectId::SessionlessInvokeRequestType_Encoding_DefaultJson
    }
    fn xml_type_id(&self) -> opcua::types::ObjectId {
        opcua::types::ObjectId::SessionlessInvokeRequestType_Encoding_DefaultXml
    }
}
impl opcua::types::BinaryEncoder for SessionlessInvokeRequestType {
    fn byte_len(&self) -> usize {
        let mut size = 0usize;
        size += self.uris_version.byte_len();
        size += self.namespace_uris.byte_len();
        size += self.server_uris.byte_len();
        size += self.locale_ids.byte_len();
        size += self.service_id.byte_len();
        size
    }
    #[allow(unused_variables)]
    fn encode<S: std::io::Write>(
        &self,
        stream: &mut S,
    ) -> opcua::types::EncodingResult<usize> {
        let mut size = 0usize;
        size += self.uris_version.encode(stream)?;
        size += self.namespace_uris.encode(stream)?;
        size += self.server_uris.encode(stream)?;
        size += self.locale_ids.encode(stream)?;
        size += self.service_id.encode(stream)?;
        Ok(size)
    }
    #[allow(unused_variables)]
    fn decode<S: std::io::Read>(
        stream: &mut S,
        decoding_options: &opcua::types::DecodingOptions,
    ) -> opcua::types::EncodingResult<Self> {
        let uris_version = <u32 as opcua::types::BinaryEncoder>::decode(
            stream,
            decoding_options,
        )?;
        let namespace_uris = <Option<
            Vec<opcua::types::string::UAString>,
        > as opcua::types::BinaryEncoder>::decode(stream, decoding_options)?;
        let server_uris = <Option<
            Vec<opcua::types::string::UAString>,
        > as opcua::types::BinaryEncoder>::decode(stream, decoding_options)?;
        let locale_ids = <Option<
            Vec<opcua::types::string::UAString>,
        > as opcua::types::BinaryEncoder>::decode(stream, decoding_options)?;
        let service_id = <u32 as opcua::types::BinaryEncoder>::decode(
            stream,
            decoding_options,
        )?;
        Ok(Self {
            uris_version,
            namespace_uris,
            server_uris,
            locale_ids,
            service_id,
        })
    }
}
