// OPCUA for Rust
// SPDX-License-Identifier: MPL-2.0
// Copyright (C) 2017-2024 Adam Lock, Einar Omang
//
// This file was autogenerated from tools/schema/schemas/1.0.4/Opc.Ua.Types.bsd by opcua-codegen
//
// DO NOT EDIT THIS FILE
#[derive(Debug, Clone, PartialEq)]
pub struct SessionSecurityDiagnosticsDataType {
    pub session_id: crate::node_id::NodeId,
    pub client_user_id_of_session: crate::string::UAString,
    pub client_user_id_history: Option<Vec<crate::string::UAString>>,
    pub authentication_mechanism: crate::string::UAString,
    pub encoding: crate::string::UAString,
    pub transport_protocol: crate::string::UAString,
    pub security_mode: super::enums::MessageSecurityMode,
    pub security_policy_uri: crate::string::UAString,
    pub client_certificate: crate::byte_string::ByteString,
}
impl crate::MessageInfo for SessionSecurityDiagnosticsDataType {
    fn object_id(&self) -> crate::ObjectId {
        crate::ObjectId::SessionSecurityDiagnosticsDataType_Encoding_DefaultBinary
    }
}
impl crate::BinaryEncoder for SessionSecurityDiagnosticsDataType {
    fn byte_len(&self) -> usize {
        let mut size = 0usize;
        size += self.session_id.byte_len();
        size += self.client_user_id_of_session.byte_len();
        size += self.client_user_id_history.byte_len();
        size += self.authentication_mechanism.byte_len();
        size += self.encoding.byte_len();
        size += self.transport_protocol.byte_len();
        size += self.security_mode.byte_len();
        size += self.security_policy_uri.byte_len();
        size += self.client_certificate.byte_len();
        size
    }
    #[allow(unused_variables)]
    fn encode<S: std::io::Write>(&self, stream: &mut S) -> crate::EncodingResult<usize> {
        let mut size = 0usize;
        size += self.session_id.encode(stream)?;
        size += self.client_user_id_of_session.encode(stream)?;
        size += self.client_user_id_history.encode(stream)?;
        size += self.authentication_mechanism.encode(stream)?;
        size += self.encoding.encode(stream)?;
        size += self.transport_protocol.encode(stream)?;
        size += self.security_mode.encode(stream)?;
        size += self.security_policy_uri.encode(stream)?;
        size += self.client_certificate.encode(stream)?;
        Ok(size)
    }
    #[allow(unused_variables)]
    fn decode<S: std::io::Read>(
        stream: &mut S,
        decoding_options: &crate::DecodingOptions,
    ) -> crate::EncodingResult<Self> {
        let session_id = <crate::node_id::NodeId as crate::BinaryEncoder>::decode(
            stream,
            decoding_options,
        )?;
        let client_user_id_of_session = <crate::string::UAString as crate::BinaryEncoder>::decode(
            stream,
            decoding_options,
        )?;
        let client_user_id_history = <Option<
            Vec<crate::string::UAString>,
        > as crate::BinaryEncoder>::decode(stream, decoding_options)?;
        let authentication_mechanism = <crate::string::UAString as crate::BinaryEncoder>::decode(
            stream,
            decoding_options,
        )?;
        let encoding = <crate::string::UAString as crate::BinaryEncoder>::decode(
            stream,
            decoding_options,
        )?;
        let transport_protocol = <crate::string::UAString as crate::BinaryEncoder>::decode(
            stream,
            decoding_options,
        )?;
        let security_mode = <super::enums::MessageSecurityMode as crate::BinaryEncoder>::decode(
            stream,
            decoding_options,
        )?;
        let security_policy_uri = <crate::string::UAString as crate::BinaryEncoder>::decode(
            stream,
            decoding_options,
        )?;
        let client_certificate = <crate::byte_string::ByteString as crate::BinaryEncoder>::decode(
            stream,
            decoding_options,
        )?;
        Ok(Self {
            session_id,
            client_user_id_of_session,
            client_user_id_history,
            authentication_mechanism,
            encoding,
            transport_protocol,
            security_mode,
            security_policy_uri,
            client_certificate,
        })
    }
}
