// OPCUA for Rust
// SPDX-License-Identifier: MPL-2.0
// Copyright (C) 2017-2024 Adam Lock, Einar Omang
//
// This file was autogenerated from tools/schema/schemas/1.0.4/Opc.Ua.Types.bsd by opcua-codegen
//
// DO NOT EDIT THIS FILE
#[derive(Debug, Clone, PartialEq)]
#[derive(Default)]
pub struct TransferSubscriptionsRequest {
    pub request_header: crate::request_header::RequestHeader,
    pub subscription_ids: Option<Vec<u32>>,
    pub send_initial_values: bool,
}
impl crate::MessageInfo for TransferSubscriptionsRequest {
    fn object_id(&self) -> crate::ObjectId {
        crate::ObjectId::TransferSubscriptionsRequest_Encoding_DefaultBinary
    }
}
impl crate::BinaryEncoder for TransferSubscriptionsRequest {
    fn byte_len(&self) -> usize {
        let mut size = 0usize;
        size += self.request_header.byte_len();
        size += self.subscription_ids.byte_len();
        size += self.send_initial_values.byte_len();
        size
    }
    #[allow(unused_variables)]
    fn encode<S: std::io::Write>(&self, stream: &mut S) -> crate::EncodingResult<usize> {
        let mut size = 0usize;
        size += self.request_header.encode(stream)?;
        size += self.subscription_ids.encode(stream)?;
        size += self.send_initial_values.encode(stream)?;
        Ok(size)
    }
    #[allow(unused_variables)]
    fn decode<S: std::io::Read>(
        stream: &mut S,
        decoding_options: &crate::DecodingOptions,
    ) -> crate::EncodingResult<Self> {
        let request_header = <crate::request_header::RequestHeader as crate::BinaryEncoder>::decode(
            stream,
            decoding_options,
        )?;
        let __request_handle = request_header.request_handle;
        let subscription_ids = <Option<
            Vec<u32>,
        > as crate::BinaryEncoder>::decode(stream, decoding_options)
            .map_err(|e| e.with_request_handle(__request_handle))?;
        let send_initial_values = <bool as crate::BinaryEncoder>::decode(
                stream,
                decoding_options,
            )
            .map_err(|e| e.with_request_handle(__request_handle))?;
        Ok(Self {
            request_header,
            subscription_ids,
            send_initial_values,
        })
    }
}
