// OPCUA for Rust
// SPDX-License-Identifier: MPL-2.0
// Copyright (C) 2017-2024 Adam Lock, Einar Omang
//
// This file was autogenerated from tools/schema/schemas/1.0.4/Opc.Ua.Types.bsd by opcua-codegen
//
// DO NOT EDIT THIS FILE
#[derive(Debug, Clone, PartialEq, Default)]
pub struct BrowsePathTarget {
    pub target_id: crate::types::expanded_node_id::ExpandedNodeId,
    pub remaining_path_index: u32,
}
impl crate::types::MessageInfo for BrowsePathTarget {
    fn object_id(&self) -> crate::types::ObjectId {
        crate::types::ObjectId::BrowsePathTarget_Encoding_DefaultBinary
    }
}
impl crate::types::BinaryEncoder<BrowsePathTarget> for BrowsePathTarget {
    fn byte_len(&self) -> usize {
        let mut size = 0usize;
        size += self.target_id.byte_len();
        size += self.remaining_path_index.byte_len();
        size
    }
    #[allow(unused_variables)]
    fn encode<S: std::io::Write>(&self, stream: &mut S) -> crate::types::EncodingResult<usize> {
        let mut size = 0usize;
        size += self.target_id.encode(stream)?;
        size += self.remaining_path_index.encode(stream)?;
        Ok(size)
    }
    #[allow(unused_variables)]
    fn decode<S: std::io::Read>(
        stream: &mut S,
        decoding_options: &crate::types::DecodingOptions,
    ) -> crate::types::EncodingResult<Self> {
        let target_id =
            <crate::types::expanded_node_id::ExpandedNodeId as crate::types::BinaryEncoder<
                crate::types::expanded_node_id::ExpandedNodeId,
            >>::decode(stream, decoding_options)?;
        let remaining_path_index =
            <u32 as crate::types::BinaryEncoder<u32>>::decode(stream, decoding_options)?;
        Ok(Self {
            target_id,
            remaining_path_index,
        })
    }
}
