// OPCUA for Rust
// SPDX-License-Identifier: MPL-2.0
// Copyright (C) 2017-2024 Adam Lock, Einar Omang
//
// This file was autogenerated from tools/schema/schemas/1.0.4/Opc.Ua.Types.bsd by opcua-codegen
//
// DO NOT EDIT THIS FILE
#[derive(Debug, Clone, PartialEq, Default)]
pub struct CallRequest {
    pub request_header: crate::types::request_header::RequestHeader,
    pub methods_to_call: Option<Vec<super::call_method_request::CallMethodRequest>>,
}
impl crate::types::MessageInfo for CallRequest {
    fn object_id(&self) -> crate::types::ObjectId {
        crate::types::ObjectId::CallRequest_Encoding_DefaultBinary
    }
}
impl crate::types::BinaryEncoder<CallRequest> for CallRequest {
    fn byte_len(&self) -> usize {
        let mut size = 0usize;
        size += self.request_header.byte_len();
        size += self.methods_to_call.byte_len();
        size
    }
    #[allow(unused_variables)]
    fn encode<S: std::io::Write>(&self, stream: &mut S) -> crate::types::EncodingResult<usize> {
        let mut size = 0usize;
        size += self.request_header.encode(stream)?;
        size += self.methods_to_call.encode(stream)?;
        Ok(size)
    }
    #[allow(unused_variables)]
    fn decode<S: std::io::Read>(
        stream: &mut S,
        decoding_options: &crate::types::DecodingOptions,
    ) -> crate::types::EncodingResult<Self> {
        let request_header =
            <crate::types::request_header::RequestHeader as crate::types::BinaryEncoder<
                crate::types::request_header::RequestHeader,
            >>::decode(stream, decoding_options)?;
        let methods_to_call = <Option<
            Vec<super::call_method_request::CallMethodRequest>,
        > as crate::types::BinaryEncoder<
            Option<Vec<super::call_method_request::CallMethodRequest>>,
        >>::decode(stream, decoding_options)?;
        Ok(Self {
            request_header,
            methods_to_call,
        })
    }
}
