// OPCUA for Rust
// SPDX-License-Identifier: MPL-2.0
// Copyright (C) 2017-2024 Adam Lock, Einar Omang
//
// This file was autogenerated from tools/schema/schemas/1.0.4/Opc.Ua.Types.bsd by opcua-codegen
//
// DO NOT EDIT THIS FILE
#[derive(Debug, Clone, PartialEq)]
pub struct DataSetReaderDataType {
    pub name: crate::types::string::UAString,
    pub enabled: bool,
    pub publisher_id: crate::types::variant::Variant,
    pub writer_group_id: u16,
    pub data_set_writer_id: u16,
    pub data_set_meta_data: super::data_set_meta_data_type::DataSetMetaDataType,
    pub data_set_field_content_mask: super::enums::DataSetFieldContentMask,
    pub message_receive_timeout: f64,
    pub key_frame_count: u32,
    pub header_layout_uri: crate::types::string::UAString,
    pub security_mode: super::enums::MessageSecurityMode,
    pub security_group_id: crate::types::string::UAString,
    pub security_key_services: Option<Vec<super::endpoint_description::EndpointDescription>>,
    pub data_set_reader_properties: Option<Vec<super::key_value_pair::KeyValuePair>>,
    pub transport_settings: crate::types::extension_object::ExtensionObject,
    pub message_settings: crate::types::extension_object::ExtensionObject,
    pub subscribed_data_set: crate::types::extension_object::ExtensionObject,
}
impl crate::types::MessageInfo for DataSetReaderDataType {
    fn object_id(&self) -> crate::types::ObjectId {
        crate::types::ObjectId::DataSetReaderDataType_Encoding_DefaultBinary
    }
}
impl crate::types::BinaryEncoder<DataSetReaderDataType> for DataSetReaderDataType {
    fn byte_len(&self) -> usize {
        let mut size = 0usize;
        size += self.name.byte_len();
        size += self.enabled.byte_len();
        size += self.publisher_id.byte_len();
        size += self.writer_group_id.byte_len();
        size += self.data_set_writer_id.byte_len();
        size += self.data_set_meta_data.byte_len();
        size += self.data_set_field_content_mask.byte_len();
        size += self.message_receive_timeout.byte_len();
        size += self.key_frame_count.byte_len();
        size += self.header_layout_uri.byte_len();
        size += self.security_mode.byte_len();
        size += self.security_group_id.byte_len();
        size += self.security_key_services.byte_len();
        size += self.data_set_reader_properties.byte_len();
        size += self.transport_settings.byte_len();
        size += self.message_settings.byte_len();
        size += self.subscribed_data_set.byte_len();
        size
    }
    #[allow(unused_variables)]
    fn encode<S: std::io::Write>(&self, stream: &mut S) -> crate::types::EncodingResult<usize> {
        let mut size = 0usize;
        size += self.name.encode(stream)?;
        size += self.enabled.encode(stream)?;
        size += self.publisher_id.encode(stream)?;
        size += self.writer_group_id.encode(stream)?;
        size += self.data_set_writer_id.encode(stream)?;
        size += self.data_set_meta_data.encode(stream)?;
        size += self.data_set_field_content_mask.encode(stream)?;
        size += self.message_receive_timeout.encode(stream)?;
        size += self.key_frame_count.encode(stream)?;
        size += self.header_layout_uri.encode(stream)?;
        size += self.security_mode.encode(stream)?;
        size += self.security_group_id.encode(stream)?;
        size += self.security_key_services.encode(stream)?;
        size += self.data_set_reader_properties.encode(stream)?;
        size += self.transport_settings.encode(stream)?;
        size += self.message_settings.encode(stream)?;
        size += self.subscribed_data_set.encode(stream)?;
        Ok(size)
    }
    #[allow(unused_variables)]
    fn decode<S: std::io::Read>(
        stream: &mut S,
        decoding_options: &crate::types::DecodingOptions,
    ) -> crate::types::EncodingResult<Self> {
        let name = <crate::types::string::UAString as crate::types::BinaryEncoder<
            crate::types::string::UAString,
        >>::decode(stream, decoding_options)?;
        let enabled =
            <bool as crate::types::BinaryEncoder<bool>>::decode(stream, decoding_options)?;
        let publisher_id = <crate::types::variant::Variant as crate::types::BinaryEncoder<
            crate::types::variant::Variant,
        >>::decode(stream, decoding_options)?;
        let writer_group_id =
            <u16 as crate::types::BinaryEncoder<u16>>::decode(stream, decoding_options)?;
        let data_set_writer_id =
            <u16 as crate::types::BinaryEncoder<u16>>::decode(stream, decoding_options)?;
        let data_set_meta_data =
            <super::data_set_meta_data_type::DataSetMetaDataType as crate::types::BinaryEncoder<
                super::data_set_meta_data_type::DataSetMetaDataType,
            >>::decode(stream, decoding_options)?;
        let data_set_field_content_mask =
            <super::enums::DataSetFieldContentMask as crate::types::BinaryEncoder<
                super::enums::DataSetFieldContentMask,
            >>::decode(stream, decoding_options)?;
        let message_receive_timeout =
            <f64 as crate::types::BinaryEncoder<f64>>::decode(stream, decoding_options)?;
        let key_frame_count =
            <u32 as crate::types::BinaryEncoder<u32>>::decode(stream, decoding_options)?;
        let header_layout_uri = <crate::types::string::UAString as crate::types::BinaryEncoder<
            crate::types::string::UAString,
        >>::decode(stream, decoding_options)?;
        let security_mode = <super::enums::MessageSecurityMode as crate::types::BinaryEncoder<
            super::enums::MessageSecurityMode,
        >>::decode(stream, decoding_options)?;
        let security_group_id = <crate::types::string::UAString as crate::types::BinaryEncoder<
            crate::types::string::UAString,
        >>::decode(stream, decoding_options)?;
        let security_key_services = <Option<
            Vec<super::endpoint_description::EndpointDescription>,
        > as crate::types::BinaryEncoder<
            Option<Vec<super::endpoint_description::EndpointDescription>>,
        >>::decode(stream, decoding_options)?;
        let data_set_reader_properties =
            <Option<Vec<super::key_value_pair::KeyValuePair>> as crate::types::BinaryEncoder<
                Option<Vec<super::key_value_pair::KeyValuePair>>,
            >>::decode(stream, decoding_options)?;
        let transport_settings =
            <crate::types::extension_object::ExtensionObject as crate::types::BinaryEncoder<
                crate::types::extension_object::ExtensionObject,
            >>::decode(stream, decoding_options)?;
        let message_settings =
            <crate::types::extension_object::ExtensionObject as crate::types::BinaryEncoder<
                crate::types::extension_object::ExtensionObject,
            >>::decode(stream, decoding_options)?;
        let subscribed_data_set =
            <crate::types::extension_object::ExtensionObject as crate::types::BinaryEncoder<
                crate::types::extension_object::ExtensionObject,
            >>::decode(stream, decoding_options)?;
        Ok(Self {
            name,
            enabled,
            publisher_id,
            writer_group_id,
            data_set_writer_id,
            data_set_meta_data,
            data_set_field_content_mask,
            message_receive_timeout,
            key_frame_count,
            header_layout_uri,
            security_mode,
            security_group_id,
            security_key_services,
            data_set_reader_properties,
            transport_settings,
            message_settings,
            subscribed_data_set,
        })
    }
}
