// OPCUA for Rust
// SPDX-License-Identifier: MPL-2.0
// Copyright (C) 2017-2024 Adam Lock, Einar Omang
//
// This file was autogenerated from tools/schema/schemas/1.0.4/Opc.Ua.Types.bsd by opcua-codegen
//
// DO NOT EDIT THIS FILE
#[derive(Debug, Clone, PartialEq, Default)]
pub struct HistoryUpdateResponse {
    pub response_header: crate::types::response_header::ResponseHeader,
    pub results: Option<Vec<super::history_update_result::HistoryUpdateResult>>,
    pub diagnostic_infos: Option<Vec<crate::types::diagnostic_info::DiagnosticInfo>>,
}
impl crate::types::MessageInfo for HistoryUpdateResponse {
    fn object_id(&self) -> crate::types::ObjectId {
        crate::types::ObjectId::HistoryUpdateResponse_Encoding_DefaultBinary
    }
}
impl crate::types::BinaryEncoder<HistoryUpdateResponse> for HistoryUpdateResponse {
    fn byte_len(&self) -> usize {
        let mut size = 0usize;
        size += self.response_header.byte_len();
        size += self.results.byte_len();
        size += self.diagnostic_infos.byte_len();
        size
    }
    #[allow(unused_variables)]
    fn encode<S: std::io::Write>(&self, stream: &mut S) -> crate::types::EncodingResult<usize> {
        let mut size = 0usize;
        size += self.response_header.encode(stream)?;
        size += self.results.encode(stream)?;
        size += self.diagnostic_infos.encode(stream)?;
        Ok(size)
    }
    #[allow(unused_variables)]
    fn decode<S: std::io::Read>(
        stream: &mut S,
        decoding_options: &crate::types::DecodingOptions,
    ) -> crate::types::EncodingResult<Self> {
        let response_header =
            <crate::types::response_header::ResponseHeader as crate::types::BinaryEncoder<
                crate::types::response_header::ResponseHeader,
            >>::decode(stream, decoding_options)?;
        let results = <Option<
            Vec<super::history_update_result::HistoryUpdateResult>,
        > as crate::types::BinaryEncoder<
            Option<Vec<super::history_update_result::HistoryUpdateResult>>,
        >>::decode(stream, decoding_options)?;
        let diagnostic_infos = <Option<
            Vec<crate::types::diagnostic_info::DiagnosticInfo>,
        > as crate::types::BinaryEncoder<
            Option<Vec<crate::types::diagnostic_info::DiagnosticInfo>>,
        >>::decode(stream, decoding_options)?;
        Ok(Self {
            response_header,
            results,
            diagnostic_infos,
        })
    }
}
