// OPCUA for Rust
// SPDX-License-Identifier: MPL-2.0
// Copyright (C) 2017-2024 Adam Lock, Einar Omang
//
// This file was autogenerated from tools/schema/schemas/1.0.4/Opc.Ua.Types.bsd by opcua-codegen
//
// DO NOT EDIT THIS FILE
#[derive(Debug, Clone, PartialEq, Default)]
pub struct SamplingIntervalDiagnosticsDataType {
    pub sampling_interval: f64,
    pub monitored_item_count: u32,
    pub max_monitored_item_count: u32,
    pub disabled_monitored_item_count: u32,
}
impl crate::types::MessageInfo for SamplingIntervalDiagnosticsDataType {
    fn object_id(&self) -> crate::types::ObjectId {
        crate::types::ObjectId::SamplingIntervalDiagnosticsDataType_Encoding_DefaultBinary
    }
}
impl crate::types::BinaryEncoder<SamplingIntervalDiagnosticsDataType>
    for SamplingIntervalDiagnosticsDataType
{
    fn byte_len(&self) -> usize {
        let mut size = 0usize;
        size += self.sampling_interval.byte_len();
        size += self.monitored_item_count.byte_len();
        size += self.max_monitored_item_count.byte_len();
        size += self.disabled_monitored_item_count.byte_len();
        size
    }
    #[allow(unused_variables)]
    fn encode<S: std::io::Write>(&self, stream: &mut S) -> crate::types::EncodingResult<usize> {
        let mut size = 0usize;
        size += self.sampling_interval.encode(stream)?;
        size += self.monitored_item_count.encode(stream)?;
        size += self.max_monitored_item_count.encode(stream)?;
        size += self.disabled_monitored_item_count.encode(stream)?;
        Ok(size)
    }
    #[allow(unused_variables)]
    fn decode<S: std::io::Read>(
        stream: &mut S,
        decoding_options: &crate::types::DecodingOptions,
    ) -> crate::types::EncodingResult<Self> {
        let sampling_interval =
            <f64 as crate::types::BinaryEncoder<f64>>::decode(stream, decoding_options)?;
        let monitored_item_count =
            <u32 as crate::types::BinaryEncoder<u32>>::decode(stream, decoding_options)?;
        let max_monitored_item_count =
            <u32 as crate::types::BinaryEncoder<u32>>::decode(stream, decoding_options)?;
        let disabled_monitored_item_count =
            <u32 as crate::types::BinaryEncoder<u32>>::decode(stream, decoding_options)?;
        Ok(Self {
            sampling_interval,
            monitored_item_count,
            max_monitored_item_count,
            disabled_monitored_item_count,
        })
    }
}
