// OPCUA for Rust
// SPDX-License-Identifier: MPL-2.0
// Copyright (C) 2017-2024 Adam Lock, Einar Omang
//
// This file was autogenerated from tools/schema/schemas/1.0.4/Opc.Ua.Types.bsd by opcua-codegen
//
// DO NOT EDIT THIS FILE
#[derive(Debug, Clone, PartialEq)]
#[derive(Default)]
pub struct SetPublishingModeRequest {
    pub request_header: crate::types::request_header::RequestHeader,
    pub publishing_enabled: bool,
    pub subscription_ids: Option<Vec<u32>>,
}
impl crate::types::MessageInfo for SetPublishingModeRequest {
    fn object_id(&self) -> crate::types::ObjectId {
        crate::types::ObjectId::SetPublishingModeRequest_Encoding_DefaultBinary
    }
}
impl crate::types::BinaryEncoder for SetPublishingModeRequest {
    fn byte_len(&self) -> usize {
        let mut size = 0usize;
        size += self.request_header.byte_len();
        size += self.publishing_enabled.byte_len();
        size += self.subscription_ids.byte_len();
        size
    }
    #[allow(unused_variables)]
    fn encode<S: std::io::Write>(
        &self,
        stream: &mut S,
    ) -> crate::types::EncodingResult<usize> {
        let mut size = 0usize;
        size += self.request_header.encode(stream)?;
        size += self.publishing_enabled.encode(stream)?;
        size += self.subscription_ids.encode(stream)?;
        Ok(size)
    }
    #[allow(unused_variables)]
    fn decode<S: std::io::Read>(
        stream: &mut S,
        decoding_options: &crate::types::DecodingOptions,
    ) -> crate::types::EncodingResult<Self> {
        let request_header = <crate::types::request_header::RequestHeader as crate::types::BinaryEncoder>::decode(
            stream,
            decoding_options,
        )?;
        let __request_handle = request_header.request_handle;
        let publishing_enabled = <bool as crate::types::BinaryEncoder>::decode(
                stream,
                decoding_options,
            )
            .map_err(|e| e.with_request_handle(__request_handle))?;
        let subscription_ids = <Option<
            Vec<u32>,
        > as crate::types::BinaryEncoder>::decode(stream, decoding_options)
            .map_err(|e| e.with_request_handle(__request_handle))?;
        Ok(Self {
            request_header,
            publishing_enabled,
            subscription_ids,
        })
    }
}
