// OPCUA for Rust
// SPDX-License-Identifier: MPL-2.0
// Copyright (C) 2017-2024 Adam Lock, Einar Omang
//
// This file was autogenerated from tools/schema/schemas/1.0.4/Opc.Ua.Types.bsd by opcua-codegen
//
// DO NOT EDIT THIS FILE
#[derive(Debug, Clone, PartialEq)]
#[derive(Default)]
pub struct StatusChangeNotification {
    pub status: crate::types::status_code::StatusCode,
    pub diagnostic_info: crate::types::diagnostic_info::DiagnosticInfo,
}
impl crate::types::BinaryEncoder for StatusChangeNotification {
    fn byte_len(&self) -> usize {
        let mut size = 0usize;
        size += self.status.byte_len();
        size += self.diagnostic_info.byte_len();
        size
    }
    #[allow(unused_variables)]
    fn encode<S: std::io::Write>(
        &self,
        stream: &mut S,
    ) -> crate::types::EncodingResult<usize> {
        let mut size = 0usize;
        size += self.status.encode(stream)?;
        size += self.diagnostic_info.encode(stream)?;
        Ok(size)
    }
    #[allow(unused_variables)]
    fn decode<S: std::io::Read>(
        stream: &mut S,
        decoding_options: &crate::types::DecodingOptions,
    ) -> crate::types::EncodingResult<Self> {
        let status = <crate::types::status_code::StatusCode as crate::types::BinaryEncoder>::decode(
            stream,
            decoding_options,
        )?;
        let diagnostic_info = <crate::types::diagnostic_info::DiagnosticInfo as crate::types::BinaryEncoder>::decode(
            stream,
            decoding_options,
        )?;
        Ok(Self { status, diagnostic_info })
    }
}
