// OPCUA for Rust
// SPDX-License-Identifier: MPL-2.0
// Copyright (C) 2017-2024 Adam Lock, Einar Omang
//
// This file was autogenerated from tools/schema/schemas/1.0.4/Opc.Ua.Types.bsd by opcua-codegen
//
// DO NOT EDIT THIS FILE
#[derive(Debug, Clone, PartialEq)]
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "PascalCase")]
pub struct StructureDefinition {
    pub default_encoding_id: crate::types::node_id::NodeId,
    pub base_data_type: crate::types::node_id::NodeId,
    pub structure_type: super::enums::StructureType,
    pub fields: Option<Vec<super::structure_field::StructureField>>,
}
impl crate::types::BinaryEncoder for StructureDefinition {
    fn byte_len(&self) -> usize {
        let mut size = 0usize;
        size += self.default_encoding_id.byte_len();
        size += self.base_data_type.byte_len();
        size += self.structure_type.byte_len();
        size += self.fields.byte_len();
        size
    }
    #[allow(unused_variables)]
    fn encode<S: std::io::Write>(
        &self,
        stream: &mut S,
    ) -> crate::types::EncodingResult<usize> {
        let mut size = 0usize;
        size += self.default_encoding_id.encode(stream)?;
        size += self.base_data_type.encode(stream)?;
        size += self.structure_type.encode(stream)?;
        size += self.fields.encode(stream)?;
        Ok(size)
    }
    #[allow(unused_variables)]
    fn decode<S: std::io::Read>(
        stream: &mut S,
        decoding_options: &crate::types::DecodingOptions,
    ) -> crate::types::EncodingResult<Self> {
        let default_encoding_id = <crate::types::node_id::NodeId as crate::types::BinaryEncoder>::decode(
            stream,
            decoding_options,
        )?;
        let base_data_type = <crate::types::node_id::NodeId as crate::types::BinaryEncoder>::decode(
            stream,
            decoding_options,
        )?;
        let structure_type = <super::enums::StructureType as crate::types::BinaryEncoder>::decode(
            stream,
            decoding_options,
        )?;
        let fields = <Option<
            Vec<super::structure_field::StructureField>,
        > as crate::types::BinaryEncoder>::decode(stream, decoding_options)?;
        Ok(Self {
            default_encoding_id,
            base_data_type,
            structure_type,
            fields,
        })
    }
}
