// OPCUA for Rust
// SPDX-License-Identifier: MPL-2.0
// Copyright (C) 2017-2024 Adam Lock, Einar Omang
//
// This file was autogenerated from tools/schema/schemas/1.0.4/Opc.Ua.Types.bsd by opcua-codegen
//
// DO NOT EDIT THIS FILE
#[derive(Debug, Clone, PartialEq)]
pub struct UserTokenPolicy {
    pub policy_id: crate::types::string::UAString,
    pub token_type: super::enums::UserTokenType,
    pub issued_token_type: crate::types::string::UAString,
    pub issuer_endpoint_url: crate::types::string::UAString,
    pub security_policy_uri: crate::types::string::UAString,
}
impl crate::types::MessageInfo for UserTokenPolicy {
    fn object_id(&self) -> crate::types::ObjectId {
        crate::types::ObjectId::UserTokenPolicy_Encoding_DefaultBinary
    }
}
impl crate::types::BinaryEncoder<UserTokenPolicy> for UserTokenPolicy {
    fn byte_len(&self) -> usize {
        let mut size = 0usize;
        size += self.policy_id.byte_len();
        size += self.token_type.byte_len();
        size += self.issued_token_type.byte_len();
        size += self.issuer_endpoint_url.byte_len();
        size += self.security_policy_uri.byte_len();
        size
    }
    #[allow(unused_variables)]
    fn encode<S: std::io::Write>(&self, stream: &mut S) -> crate::types::EncodingResult<usize> {
        let mut size = 0usize;
        size += self.policy_id.encode(stream)?;
        size += self.token_type.encode(stream)?;
        size += self.issued_token_type.encode(stream)?;
        size += self.issuer_endpoint_url.encode(stream)?;
        size += self.security_policy_uri.encode(stream)?;
        Ok(size)
    }
    #[allow(unused_variables)]
    fn decode<S: std::io::Read>(
        stream: &mut S,
        decoding_options: &crate::types::DecodingOptions,
    ) -> crate::types::EncodingResult<Self> {
        let policy_id = <crate::types::string::UAString as crate::types::BinaryEncoder<
            crate::types::string::UAString,
        >>::decode(stream, decoding_options)?;
        let token_type = <super::enums::UserTokenType as crate::types::BinaryEncoder<
            super::enums::UserTokenType,
        >>::decode(stream, decoding_options)?;
        let issued_token_type = <crate::types::string::UAString as crate::types::BinaryEncoder<
            crate::types::string::UAString,
        >>::decode(stream, decoding_options)?;
        let issuer_endpoint_url =
            <crate::types::string::UAString as crate::types::BinaryEncoder<
                crate::types::string::UAString,
            >>::decode(stream, decoding_options)?;
        let security_policy_uri =
            <crate::types::string::UAString as crate::types::BinaryEncoder<
                crate::types::string::UAString,
            >>::decode(stream, decoding_options)?;
        Ok(Self {
            policy_id,
            token_type,
            issued_token_type,
            issuer_endpoint_url,
            security_policy_uri,
        })
    }
}
